#!/bin/bash
#SBATCH -J JOB_NAME
#SBATCH -p thin
#SBATCH -n 128
#SBATCH --mem=128G
#SBATCH --exclusive
#SBATCH -t 1-00:00:00

module load 2022
module load OpenMPI/4.1.4-GCC-11.3.0

lmp=~/lammps/la*18/src/
srun $lmp/lmp_mpi < simulation.in

wait

exit 0 
