#!/bin/bash
#SBATCH --job-name="KCl T is 298 m is 4 run 1"
#SBATCH -n 48
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=1G

module load 2022r2
module load openmpi

lmp=~/software/lammps/lammps2018/src/ # getting the correct run file location
srun $lmp/lmp_mpi < simulation.in # computing with n cpu cores.
wait

exit 0
