#!/bin/bash
#SBATCH --job-name="KCl T is 298 m is 4 run 1"
#SBATCH -p parallel-12
#SBATCH -n 12
#SBATCH --mem-per-cpu=2G
#SBATCH -t 6-00:00:00

lmp=~/software/lammps/lam*18/src/ # getting the correct run file location
mpirun $lmp/lmp_mpi < simulation.in # computing with n cpu cores.
wait

exit 0
